modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"
[[mods]]
modId="multicore_lib"
version="${file.jarVersion}"
displayName="MultiCore-Lib"
logoFile="multicore_lib_logo.png"
credits="Made by MultiTeam"
authors="LazTheArtist, Qboi"
description='''
This mod is a Library, for tools and helpers, to make coding mods faster and easier.

LazTheArtist [HoverTextItemTool - ItemGroupTool - ItemManagementTool - MathF - RegistrationTool - TeleportTool]
Qboi [Maven Setup]
'''
[[dependencies.multicore_lib]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.multicore_lib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
